### ISSUE TITLE
Suggestion: fetch api alternative solutions

### ISSUE THREAD

**Issue by winetree94** [ktock/container2wasm#303]
Hello,

Thank you for your fantastic project. I'm looking into ways to integrate this project into modern web applications.

Currently, using browser network fetches causes two main issues:
- CORS Problem: Requests to third-party sites fail.
- Mixed Content Problem: HTTP (non-SSL) requests fail.

To address these issues, I've created a small Chrome extension. This extension ensures all browser requests are performed by the extension itself. (When fetch requests are made from the Chrome extension, CORS and mixed content errors do not occur.)

While it's unfortunate that installation is required, I believe this is the simplest way to enable network functionality effectively at the moment.

Source code: [GitHub](https://github.com/winetree94/C2W-Web-Starter/tree/main/packages/proxy)
Download extension: [here](https://c2w-playground.pages.dev/c2w_proxy.zip)
Test demo: [here](https://c2w-playground.pages.dev)

You can extract the files and load the extension by selecting 'Load unpacked' at chrome://extensions/. Currently, it only works on my website as the example needs modification.

I would love to hear your thoughts on this idea. Thank you.

**Comment by ktock** [comment]
Thanks for the suggestion! Using browser extensions sounds cool solution for that problem. Though the current scope of this project is to make it work without extensions, I'm grad hear to that your extension works well with container2wasm. For now, I'll close this issue  because using extension isn't in the current scope of this project but please let me know if there are any issues on c2w's side when using it with your extension. Of course feel free to reopen this if you have further proposal. Thanks for trying this project!
